'use client';

export const mockSellers: Record<string, { id: string; name: string; avatarUrl: string; rating: number; reviewsCount: number }> = {
  u1: {
    id: 'u1',
    name: 'María Gómez',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop',
    rating: 4.8,
    reviewsCount: 12,
  },
  u2: {
    id: 'u2',
    name: 'Carlos Martín',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop',
    rating: 4.5,
    reviewsCount: 8,
  },
  u3: {
    id: 'u3',
    name: 'Ana López',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop',
    rating: 5.0,
    reviewsCount: 15,
  },
};

export const mockProducts = [
  {
    id: 'p1',
    title: 'Matemáticas 3º Primaria',
    price: 15,
    imageUrl: 'https://images.unsplash.com/photo-150784272343-583f20270319?w=200&h=200&fit=crop',
    condition: 'Buen estado',
    course: '3º Primaria',
    state: 'active' as const,
    description: 'Libro de Matemáticas sin escribir. Incluye CD con ejercicios.',
    sellerId: 'u1',
  },
  {
    id: 'p2',
    title: 'Uniforme Colegio Talla M',
    price: 35,
    imageUrl: 'https://images.unsplash.com/photo-1618886723857-ba0b32e2a1e9?w=200&h=200&fit=crop',
    condition: 'Como nuevo',
    course: 'Primaria',
    state: 'active' as const,
    description: 'Uniforme completo: falda, blusa y corbata. Poco usado.',
    sellerId: 'u2',
  },
  {
    id: 'p3',
    title: 'Mochila Escolar 25L',
    price: 25,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=200&h=200&fit=crop',
    condition: 'Buen estado',
    course: 'ESO',
    state: 'reserved' as const,
    description: 'Mochila ergonómica en azul marino. Con bolsillos para portátil.',
    sellerId: 'u3',
  },
  {
    id: 'p4',
    title: 'Diccionario Inglés-Español',
    price: 12,
    imageUrl: 'https://images.unsplash.com/photo-1507842721554-8ee5dd3f7e26?w=200&h=200&fit=crop',
    condition: 'Muy usado',
    course: '1º ESO',
    state: 'active' as const,
    description: 'Diccionario con notas. Sirve para clase de inglés.',
    sellerId: 'u1',
  },
  {
    id: 'p5',
    title: 'Cuadernos Rayados Lote',
    price: 8,
    imageUrl: 'https://images.unsplash.com/photo-1507842821343-583f20270319?w=200&h=200&fit=crop',
    condition: 'Sin usar',
    course: 'Todos',
    state: 'active' as const,
    description: 'Lote de 5 cuadernos A4 de 100 hojas sin rayar.',
    sellerId: 'u2',
  },
  {
    id: 'p6',
    title: 'Calculadora Científica',
    price: 20,
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f5ae4e8b08f?w=200&h=200&fit=crop',
    condition: 'Buen estado',
    course: '3º ESO',
    state: 'sold' as const,
    description: 'Calculadora científica modelo CASIO FX-82MS.',
    sellerId: 'u3',
  },
];
